name: Driver
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Test with Maven
        run: mvn -B verify

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: KD131/cicd-integration-test-demo/.github/workflows/deploy.yml@main
    secrets: inherit
